### ISSUE TITLE
Text-align & margin width

### ISSUE THREAD

**Issue by trebird** [trebird/sections#1]
Hi again

Just having trouble with text-align for the button. I've made everything in the section centered, but the button won't align left even within the parent element. 

Also, I'm not sure what margin value is expected inside the body.

Thank you @thomasjbradley

**Comment by thomasjbradley** [comment]
The `margin` for `body` is almost always going to be `0`.

---

For the button, it’ll be easier if you surround it in another element, maybe surround it in another `<div>` and add the `text-align: left` to that.
